### ISSUE TITLE
No such table errors

### ISSUE THREAD

**Issue by CoreyWDavis** [kevinrmblr/traceprivately-server#1]
I am trying to quickly get the server up and running for some basic testing but am running into errors. I followed the directions for running through Xcode (11.5) and have edited the working directory under Edit Scheme->Run. The server seems to start fine, but when opening http://localhost:8080 I get `{"error":true,"reason":"error: no such table: tracing_key_batch"}`. I have also tried running the Trace Privately app and get errors. This is from the Xcode for the server:

`[ NOTICE ] Server starting on http://127.0.0.1:8080
[ INFO ] GET /
[ INFO ] query read tracing_key_batch
[ ERROR ] error: no such table: tracing_key_batch
[ INFO ] POST /api/auth
[ INFO ] query create device input=[[created_at: 2020-06-12 05:17:53 +0000, token_expiration_date: 2020-06-19 05:17:53 +0000, token: "416FA20A-D717-4C44-87F7-921A88D39840", updated_at: 2020-06-12 05:17:53 +0000, id: BD73D14B-C554-48AF-B0B4-1B27F543B49A]]
[ ERROR ] error: no such table: device
[ INFO ] POST /api/auth
[ INFO ] query create device input=[[token: "4804334A-B95C-4409-A8E1-AB0F28D866DC", id: FC893E91-DB2C-4BB6-834E-7F57B2B1FFE8, token_expiration_date: 2020-06-19 05:17:54 +0000, created_at: 2020-06-12 05:17:54 +0000, updated_at: 2020-06-12 05:17:54 +0000]]
[ ERROR ] error: no such table: device`

Is there something I need to do to setup the databse?

**Comment by kevinrmblr** [comment]
Hi @CoreyWDavis,

Sorry for the late reaction!

It seems I forgot to mention to add two arguments on launch:

- Press the build target in the top, select `edit scheme...`
- Under Run -> Arguments, add these two lines to 'Arguments Passed On Launch':
  - `--auto-migrate`
  - `serve --hostname 0.0.0.0 --port 8080`

The first argument tells Vapor to create (or update) the database if needed, the latter allow the app to listen to the port on your local network.

I'll also update the readme file later.

![Screenshot 2020-06-16 at 16 05 57](https://user-images.githubusercontent.com/236215/84785231-8adaec80-afeb-11ea-8d38-40964fda9b32.png)

**Comment by kevinrmblr** [comment]
Hi @CoreyWDavis,

Were you able to run the project with the mentioned changes?

**Comment by corey-plugshare** [comment]
@kevinrmblr sorry, things got busy with another project. I will try and get back to you. Thanks!

**Comment by corey-plugshare** [comment]
It looks like this resolved the issue. Thanks!

**Comment by kevinrmblr** [comment]
Great to hear!
